//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BWJS.SMS.HuaXinSMS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.yysms.com/", ConfigurationName="HuaXinSMS.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yysms.com/SendSms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BWJS.SMS.HuaXinSMS.SendResult SendSms(string userName, string password, BWJS.SMS.HuaXinSMS.SmsObject sms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yysms.com/SendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<BWJS.SMS.HuaXinSMS.SendResult> SendSmsAsync(string userName, string password, BWJS.SMS.HuaXinSMS.SmsObject sms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yysms.com/SendMms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BWJS.SMS.HuaXinSMS.SendResult SendMms(string userName, string password, BWJS.SMS.HuaXinSMS.MmsObject mms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yysms.com/SendMms", ReplyAction="*")]
        System.Threading.Tasks.Task<BWJS.SMS.HuaXinSMS.SendResult> SendMmsAsync(string userName, string password, BWJS.SMS.HuaXinSMS.MmsObject mms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yysms.com/SendI18NSms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BWJS.SMS.HuaXinSMS.SendResultBase SendI18NSms(string userName, string password, BWJS.SMS.HuaXinSMS.SmsObject sms);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.yysms.com/SendI18NSms", ReplyAction="*")]
        System.Threading.Tasks.Task<BWJS.SMS.HuaXinSMS.SendResultBase> SendI18NSmsAsync(string userName, string password, BWJS.SMS.HuaXinSMS.SmsObject sms);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yysms.com/")]
    public partial class SmsObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msisdnsField;
        
        private string sMSContentField;
        
        private string extNumberField;
        
        private System.Nullable<System.DateTime> planSendTimeField;
        
        private string noPassField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Msisdns {
            get {
                return this.msisdnsField;
            }
            set {
                this.msisdnsField = value;
                this.RaisePropertyChanged("Msisdns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SMSContent {
            get {
                return this.sMSContentField;
            }
            set {
                this.sMSContentField = value;
                this.RaisePropertyChanged("SMSContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ExtNumber {
            get {
                return this.extNumberField;
            }
            set {
                this.extNumberField = value;
                this.RaisePropertyChanged("ExtNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> PlanSendTime {
            get {
                return this.planSendTimeField;
            }
            set {
                this.planSendTimeField = value;
                this.RaisePropertyChanged("PlanSendTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NoPass {
            get {
                return this.noPassField;
            }
            set {
                this.noPassField = value;
                this.RaisePropertyChanged("NoPass");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yysms.com/")]
    public partial class MmsElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private MmsElementType elementTypeField;
        
        private string base64TextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MmsElementType ElementType {
            get {
                return this.elementTypeField;
            }
            set {
                this.elementTypeField = value;
                this.RaisePropertyChanged("ElementType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Base64Text {
            get {
                return this.base64TextField;
            }
            set {
                this.base64TextField = value;
                this.RaisePropertyChanged("Base64Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yysms.com/")]
    public enum MmsElementType {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        Jpg,
        
        /// <remarks/>
        Gif,
        
        /// <remarks/>
        Png,
        
        /// <remarks/>
        Bmp,
        
        /// <remarks/>
        Smil,
        
        /// <remarks/>
        Wav,
        
        /// <remarks/>
        Mid,
        
        /// <remarks/>
        Amr,
        
        /// <remarks/>
        Mp3,
        
        /// <remarks/>
        Text,
        
        /// <remarks/>
        Xml,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yysms.com/")]
    public partial class MmsObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msisdnsField;
        
        private string subjectField;
        
        private string extNumberField;
        
        private System.Nullable<System.DateTime> planSendTimeField;
        
        private MmsElement[] elementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Msisdns {
            get {
                return this.msisdnsField;
            }
            set {
                this.msisdnsField = value;
                this.RaisePropertyChanged("Msisdns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("Subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ExtNumber {
            get {
                return this.extNumberField;
            }
            set {
                this.extNumberField = value;
                this.RaisePropertyChanged("ExtNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> PlanSendTime {
            get {
                return this.planSendTimeField;
            }
            set {
                this.planSendTimeField = value;
                this.RaisePropertyChanged("PlanSendTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public MmsElement[] Elements {
            get {
                return this.elementsField;
            }
            set {
                this.elementsField = value;
                this.RaisePropertyChanged("Elements");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(I18NSendResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SendResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yysms.com/")]
    public abstract partial class SendResultBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int payTypeField;
        
        private ResultCode statusCodeField;
        
        private string descriptionField;
        
        private string msgIdField;
        
        private int successCountsField;
        
        private int billingCountField;
        
        private long amountField;
        
        private decimal balanceField;
        
        private decimal billingAmountField;
        
        private string[] errorsField;
        
        private SendResultBase alterSendResultField;
        
        private string customIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PayType {
            get {
                return this.payTypeField;
            }
            set {
                this.payTypeField = value;
                this.RaisePropertyChanged("PayType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ResultCode StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MsgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
                this.RaisePropertyChanged("MsgId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int SuccessCounts {
            get {
                return this.successCountsField;
            }
            set {
                this.successCountsField = value;
                this.RaisePropertyChanged("SuccessCounts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int BillingCount {
            get {
                return this.billingCountField;
            }
            set {
                this.billingCountField = value;
                this.RaisePropertyChanged("BillingCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("Balance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal BillingAmount {
            get {
                return this.billingAmountField;
            }
            set {
                this.billingAmountField = value;
                this.RaisePropertyChanged("BillingAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public SendResultBase AlterSendResult {
            get {
                return this.alterSendResultField;
            }
            set {
                this.alterSendResultField = value;
                this.RaisePropertyChanged("AlterSendResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CustomId {
            get {
                return this.customIdField;
            }
            set {
                this.customIdField = value;
                this.RaisePropertyChanged("CustomId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yysms.com/")]
    public enum ResultCode {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        AppInactive,
        
        /// <remarks/>
        ParamError,
        
        /// <remarks/>
        UserNameEmpty,
        
        /// <remarks/>
        PasswordEmpty,
        
        /// <remarks/>
        UserNameError,
        
        /// <remarks/>
        PasswordError,
        
        /// <remarks/>
        BindIpError,
        
        /// <remarks/>
        UserStop,
        
        /// <remarks/>
        UserIdError,
        
        /// <remarks/>
        Text64Error,
        
        /// <remarks/>
        StampError,
        
        /// <remarks/>
        SendTimeError,
        
        /// <remarks/>
        JsonError,
        
        /// <remarks/>
        MsisdnEmpty,
        
        /// <remarks/>
        MsisdnRepeat,
        
        /// <remarks/>
        NoChannel,
        
        /// <remarks/>
        MsisdnError,
        
        /// <remarks/>
        MsisdnBlack,
        
        /// <remarks/>
        MsisdnNoChannel,
        
        /// <remarks/>
        AmountNotEnough,
        
        /// <remarks/>
        NoProduct,
        
        /// <remarks/>
        ExtNumberError,
        
        /// <remarks/>
        BalanceNotEnough,
        
        /// <remarks/>
        ChannelTypeError,
        
        /// <remarks/>
        TemplateError,
        
        /// <remarks/>
        FrequentOperation,
        
        /// <remarks/>
        NoEnabled,
        
        /// <remarks/>
        TemplateIdError,
        
        /// <remarks/>
        ContentEmpty,
        
        /// <remarks/>
        ContentLong,
        
        /// <remarks/>
        ContentError,
        
        /// <remarks/>
        MsisdnsMany,
        
        /// <remarks/>
        SensitiveWords,
        
        /// <remarks/>
        RequiredSuffix,
        
        /// <remarks/>
        SuffixError,
        
        /// <remarks/>
        SubjectEmpty,
        
        /// <remarks/>
        SubjectLong,
        
        /// <remarks/>
        FramesEmpty,
        
        /// <remarks/>
        ElementError,
        
        /// <remarks/>
        FrameError,
        
        /// <remarks/>
        FrameSizeLong,
        
        /// <remarks/>
        SmilEmpty,
        
        /// <remarks/>
        SmilExcessive,
        
        /// <remarks/>
        ElementNameRepeat,
        
        /// <remarks/>
        SizeLong,
        
        /// <remarks/>
        TaskIdEmpty,
        
        /// <remarks/>
        FaileList,
        
        /// <remarks/>
        InternalError,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yysms.com/")]
    public partial class I18NSendResult : SendResultBase {
        
        private string markField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Mark {
            get {
                return this.markField;
            }
            set {
                this.markField = value;
                this.RaisePropertyChanged("Mark");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yysms.com/")]
    public partial class SendResult : SendResultBase {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : BWJS.SMS.HuaXinSMS.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<BWJS.SMS.HuaXinSMS.WebServiceSoap>, BWJS.SMS.HuaXinSMS.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BWJS.SMS.HuaXinSMS.SendResult SendSms(string userName, string password, BWJS.SMS.HuaXinSMS.SmsObject sms) {
            return base.Channel.SendSms(userName, password, sms);
        }
        
        public System.Threading.Tasks.Task<BWJS.SMS.HuaXinSMS.SendResult> SendSmsAsync(string userName, string password, BWJS.SMS.HuaXinSMS.SmsObject sms) {
            return base.Channel.SendSmsAsync(userName, password, sms);
        }
        
        public BWJS.SMS.HuaXinSMS.SendResult SendMms(string userName, string password, BWJS.SMS.HuaXinSMS.MmsObject mms) {
            return base.Channel.SendMms(userName, password, mms);
        }
        
        public System.Threading.Tasks.Task<BWJS.SMS.HuaXinSMS.SendResult> SendMmsAsync(string userName, string password, BWJS.SMS.HuaXinSMS.MmsObject mms) {
            return base.Channel.SendMmsAsync(userName, password, mms);
        }
        
        public BWJS.SMS.HuaXinSMS.SendResultBase SendI18NSms(string userName, string password, BWJS.SMS.HuaXinSMS.SmsObject sms) {
            return base.Channel.SendI18NSms(userName, password, sms);
        }
        
        public System.Threading.Tasks.Task<BWJS.SMS.HuaXinSMS.SendResultBase> SendI18NSmsAsync(string userName, string password, BWJS.SMS.HuaXinSMS.SmsObject sms) {
            return base.Channel.SendI18NSmsAsync(userName, password, sms);
        }
    }
}
